apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest

metadata:
  name: mv

spec:
  request: dEVEVMTUFrR0ExVUVBd3dDYlhZd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUINCkR3QXdnZ0VLQW9JQkFRQ29QUGE1bzltcGsrY1oxTlFGNjdObXRjNXpjQU9TQXBxWXV5VytuL1kwbFJIbllKZUUNCktkOEtYSmF6Z1JoUE1JM21ydEZNZlE3ekZBNEU3R0h6K2dSV0wxdzhZZ1hlSCtibEFNT2M2UjYzVld3R3Jra1YNCml4R3FLdkIxaXZzdnEyNUcwdTMxZXcwclBpNnYyTU1nVnZsa0FtczE0U2NReS9SZ2dMajdsRnNGekZramZWV00NCitTOVErdEQ3c3dGbmZmK253S1A1T1dPbUpxdGRac0xZVUpncFZ5aThyb2pGZlgvL3FQQ3BXZmNLT0FCYnJPSzQNCnMreUl4QktmSE9DaDJrTk1yYXFuZ0tmWC83T0JuYnY5WFVPNmI0NUMwMzcvTkJiTUJFTXY3THlpTDA3L2U0bkQNCkQ4ZXUwanFXYXJUUW43V1RDZE9LRm85UXlYYnVBaWNWdUxkZkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQkFRc0YNCkFBT0NBUUVBcGs2R212MUpKRFphOU5hYk81UWZ3L2RwQWVjUUp2RGZXcU44VHJDdnladklNcjV0amlmbEtSRFQNCjYyT2VkbmtITTMrSHBqRXc2MkdieDlLbWRtVUVWdFVLazJIaENvQW5MekZkSmRMQWFmUENuWEhSRUhOSm9uTkMNCnBZeXZseE94Z1lTR0p0VHRYckNPNzVBMjdtTUlmTlRwV3JYTGVUK0REZUltbUlyVWc1RXNHaThoejdCaS9FY0UNCmtqeUpPZjBNQnk5cTgxTzBQUDBlS2dzRmJHQlBaZTdsRzI2Y09pbDNiNzh5R21wdFRRNkJUQWd3Mkx3VGhOdU4NCjhHVUNveTNENlFJTk1CbExkbFMwZWRLM1NGdlZLUGpWZml1dXBKNXBuKzM3SkppNytmZHRaUDZWSTVwUjFxWFcNCjBBenRPaVdCQUI3WjRsNVBjSng5NC9EeEtTeFEwZz09DQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==

  signerName: kubernetes.io/kube-apiserver-client

  expirationSeconds: 864000

  usages:
    - client auth
